version: '3.0'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  app:
    container_name: cocon_app
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 3000:3000

volumes:
  mongo: {}
